// オフライン用 Service Worker。ASSETS は tools/update-sw.mjs で自動生成する（手で書かない）
const VERSION = 'bea1a1d228';
const CACHE = `brain-escape-${VERSION}`;
const ASSETS = [
  './',
  './art/banner-en.jpg',
  './art/banner-exam.jpg',
  './art/banner-math.jpg',
  './art/banner-memory.jpg',
  './art/bg-en-1.jpg',
  './art/bg-en-2.jpg',
  './art/bg-en-3.jpg',
  './art/bg-home.jpg',
  './art/bg-math-1.jpg',
  './art/bg-math-2.jpg',
  './art/bg-math-3.jpg',
  './art/boss-angles.png',
  './art/boss-circle-angle.png',
  './art/boss-congruence.png',
  './art/boss-data.png',
  './art/boss-en-3sg.png',
  './art/boss-en-be.png',
  './art/boss-en-compare.png',
  './art/boss-en-conj.png',
  './art/boss-en-future.png',
  './art/boss-en-indirect.png',
  './art/boss-en-inf.png',
  './art/boss-en-modal.png',
  './art/boss-en-participle.png',
  './art/boss-en-passive.png',
  './art/boss-en-past.png',
  './art/boss-en-pastprog.png',
  './art/boss-en-perfect.png',
  './art/boss-en-plural.png',
  './art/boss-en-prog.png',
  './art/boss-en-relative.png',
  './art/boss-en-subjunctive.png',
  './art/boss-en-there.png',
  './art/boss-en-wh.png',
  './art/boss-en-words1.png',
  './art/boss-en-words2.png',
  './art/boss-en-words3.png',
  './art/boss-expand-factor.png',
  './art/boss-expressions.png',
  './art/boss-fractions-decimals.png',
  './art/boss-linear-equations.png',
  './art/boss-linear-function.png',
  './art/boss-polynomials.png',
  './art/boss-probability.png',
  './art/boss-proportion.png',
  './art/boss-pythagoras.png',
  './art/boss-quadratic-function.png',
  './art/boss-quadratic.png',
  './art/boss-signed-numbers.png',
  './art/boss-similarity.png',
  './art/boss-simultaneous.png',
  './art/boss-solids.png',
  './art/boss-square-roots.png',
  './art/boss-word-mix.png',
  './art/card-banana-car.png',
  './art/card-broccoli.png',
  './art/card-cheese.png',
  './art/card-crown.png',
  './art/card-duck.png',
  './art/card-moai.png',
  './art/card-onigiri.png',
  './art/card-pigeon.png',
  './art/card-robot.png',
  './art/card-snail.png',
  './art/card-sushi.png',
  './art/card-toast.png',
  './art/enemy-grunt.png',
  './art/enemy-review.png',
  './art/enemy-runner.png',
  './art/enemy-tank.png',
  './art/gacha-machine.png',
  './art/skin-candy-beam.png',
  './art/skin-candy-bomb.png',
  './art/skin-candy-frost.png',
  './art/skin-gold-beam.png',
  './art/skin-gold-bomb.png',
  './art/skin-gold-frost.png',
  './art/skin-lava-beam.png',
  './art/skin-lava-bomb.png',
  './art/skin-lava-frost.png',
  './art/skin-neon-beam.png',
  './art/skin-neon-bomb.png',
  './art/skin-neon-frost.png',
  './art/skin-pixel-beam.png',
  './art/skin-pixel-bomb.png',
  './art/skin-pixel-frost.png',
  './art/tower-beam-1.png',
  './art/tower-beam-2.png',
  './art/tower-beam-3.png',
  './art/tower-bomb-1.png',
  './art/tower-bomb-2.png',
  './art/tower-bomb-3.png',
  './art/tower-frost-1.png',
  './art/tower-frost-2.png',
  './art/tower-frost-3.png',
  './css/app.css',
  './icons/icon-180.png',
  './icons/icon-192.png',
  './icons/icon-512.png',
  './index.html',
  './js/core/check.js',
  './js/core/fmt.js',
  './js/core/frac.js',
  './js/core/mathml.js',
  './js/core/poly.js',
  './js/core/rng.js',
  './js/core/router.js',
  './js/core/sound.js',
  './js/core/store.js',
  './js/core/timer.js',
  './js/core/ui.js',
  './js/exam/en-exam-data.js',
  './js/exam/exam.js',
  './js/exam/shiga-english.js',
  './js/exam/shiga-math.js',
  './js/game/advice.js',
  './js/game/art-manifest.js',
  './js/game/art.js',
  './js/game/bonus.js',
  './js/game/content.js',
  './js/game/engine.js',
  './js/game/missions.js',
  './js/game/progress.js',
  './js/game/reward.js',
  './js/game/waves.js',
  './js/main.js',
  './js/memory/courses.js',
  './js/memory/decks/en.js',
  './js/memory/decks/sci.js',
  './js/memory/decks/soc.js',
  './js/memory/decks/terms.js',
  './js/memory/defense.js',
  './js/memory/engine.js',
  './js/memory/flow.js',
  './js/screens/battle.js',
  './js/screens/collection.js',
  './js/screens/diagnosis.js',
  './js/screens/exam.js',
  './js/screens/home.js',
  './js/screens/map.js',
  './js/screens/memdef.js',
  './js/screens/memory.js',
  './js/screens/onboarding.js',
  './js/screens/records.js',
  './js/screens/result.js',
  './js/screens/settings.js',
  './js/screens/timeattack.js',
  './js/screens/training.js',
  './js/ui/answer.js',
  './js/ui/asklater.js',
  './js/ui/board.js',
  './js/ui/deco.js',
  './js/ui/gems.js',
  './js/ui/ready.js',
  './js/ui/speech.js',
  './js/units/english/en-3sg.js',
  './js/units/english/en-be.js',
  './js/units/english/en-compare.js',
  './js/units/english/en-conj.js',
  './js/units/english/en-future.js',
  './js/units/english/en-indirect.js',
  './js/units/english/en-inf.js',
  './js/units/english/en-modal.js',
  './js/units/english/en-participle.js',
  './js/units/english/en-passive.js',
  './js/units/english/en-past.js',
  './js/units/english/en-pastprog.js',
  './js/units/english/en-perfect.js',
  './js/units/english/en-plural.js',
  './js/units/english/en-prog.js',
  './js/units/english/en-relative.js',
  './js/units/english/en-subjunctive.js',
  './js/units/english/en-there.js',
  './js/units/english/en-wh.js',
  './js/units/english/en-words1.js',
  './js/units/english/en-words2.js',
  './js/units/english/en-words3.js',
  './js/units/english/gram.js',
  './js/units/english/kit-en.js',
  './js/units/english/lex.js',
  './js/units/english/words1.js',
  './js/units/english/words2.js',
  './js/units/english/words3.js',
  './js/units/kit.js',
  './js/units/registry.js',
  './js/units/stage1/expressions.js',
  './js/units/stage1/fractions-decimals.js',
  './js/units/stage1/linear-equations.js',
  './js/units/stage1/signed-numbers.js',
  './js/units/stage2/expand-factor.js',
  './js/units/stage2/polynomials.js',
  './js/units/stage2/quadratic.js',
  './js/units/stage2/simultaneous.js',
  './js/units/stage2/square-roots.js',
  './js/units/stage3/angles.js',
  './js/units/stage3/circle-angle.js',
  './js/units/stage3/congruence.js',
  './js/units/stage3/data.js',
  './js/units/stage3/fig.js',
  './js/units/stage3/kit3.js',
  './js/units/stage3/linear-function.js',
  './js/units/stage3/probability.js',
  './js/units/stage3/proportion.js',
  './js/units/stage3/pythagoras.js',
  './js/units/stage3/quadratic-function.js',
  './js/units/stage3/similarity.js',
  './js/units/stage3/solids.js',
  './js/units/stage3/word-mix.js',
  './manifest.webmanifest',
];

// cache: 'reload' … ブラウザに残っている古いファイル（HTTP キャッシュ）を使わず、必ずサーバーから取る。
// これがないと、新しい版のキャッシュに古いファイルが入って、アップロードしても画面が変わらないことがある
self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS.map((u) => new Request(u, { cache: 'reload' })))).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('brain-escape-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

// キャッシュ優先。なければネットから取って保存（同じサイトのファイルだけ）
self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;
  e.respondWith(
    caches.match(req, { ignoreSearch: true }).then((hit) => hit || fetch(req).then((res) => {
      if (res.ok) {
        const copy = res.clone();
        caches.open(CACHE).then((c) => c.put(req, copy));
      }
      return res;
    }).catch(() => caches.match('./index.html'))),
  );
});
